:Author: ard12sgf1960
:Email: sgfpcb@gmail.com
:Date: 05/11/2023
:Revision: version#1.0
:License: Public Domain

= Project: {Remote relay control via Arduino IOT Cloud}

Control an M5 Relay Module using a M5 Atom S3 connected to Arduino IOT

== Step 1: Installation

Connect the Relay Module to the Atom

== Step 2: Assemble the circuit

1. Change the WiFi Credentials on arduino_secrets.h
2. Upload the code contained in this sketch on to your board

=== Folder structure

....
 M5_Atom_S3                  => Arduino sketch folder
  ├── M5_Atom_S3_nov05a.ino  => main Arduino file
  ├── thingProperties.h      => Arduino created library
  ├── arduino_secrets.h      => library that contains WiFi Credentials
  ├── atomHelper.h           => library file to manager the Atom
  └── relayHelper.h          => library file to manager the Relay module
....

=== License
This project is released under a {PUBLIC} License.

=== Contributing
To contribute to this project please contact: sgfpcb@gmail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name       | Part number | Quantity
| A1 | M5 Atom S3      | 1234-abcd   | 1    
| A2 | M5 Relay Module | 2345-asdf   | 1             
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
