:Author: ard12sgf1960
:Email:
:Date: 05/11/2023
:Revision: version#
:License: Public Domain

= Project: {Atom S3, Relay Module and Arduino IOT}

Using an Atom S3 with a Relay Module using Arduino Cloud IOT

== Step 1: Installation

1. Connect the Relay Module to the Atom
2. Connect the Aton to a PC with Arduino IDE installed
3. Change the WiFi Credentials in the arduino_secrets.h file
4. Upload to the device

=== Folder structure

....
 Atom_S3_Relay            => Arduino sketch folder
  ├── thingProperties.h   => Arduino IOT library
  ├── atomHelper.h        => local library for Atom 
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
