:Author: ard12sgf1960
:Email: sgfpcb@gmail.com
:Date: 05/11/2023
:Revision: version#1.0
:License: Public Domain

= Project: {Remote relay control via Arduino IOT Cloud}

Control an M5 Relay Module using a M5 Atom S3 connected to Arduino IOT

== Step 1: Installation

1. Connect the Relay Module to the Atom
2. Connect the Atom as a Device on Arduino and obtain its secret device key
3. Connect as a switch using the NC, NO, C connections

To connect LED Christmas Lamps
1. Cut one of the Low Voltage Transformer output cables 
2. Connect one side to C and the other to NO.

== Step 2: Assemble the circuit

1. Change the WiFi Credentials in arduino_secrets.h using Notepad or similar text editor
   #define SECRET_DEVICE_KEY "XXXXXXX"
   #define SECRET_OPTIONAL_PASS "XXXXXXX"
   #define SECRET_SSID "XXXXXXX"
2. Upload the code contained in this sketch on to your board

== Step 3: Operation

1. The Atom will try and connect to you WiFi
2. When successful, the display will show a ~ either side of the display
3. Switch the relay by pressing the display OR
4. Use a Dashboard in Arduino

=== Folder structure

....
 M5_Atom_S3                  => Arduino sketch folder
  ├── M5_Atom_S3_nov05a.ino  => main Arduino file
  ├── thingProperties.h      => Arduino created library
  ├── arduino_secrets.h      => library that contains WiFi Credentials
  ├── atomHelper.h           => library file to manager the Atom
  ├── relayHelper.h          => library file to manage the Relay module
  └── WiFiHelper.h           => library file to manage internet connection  
....

=== License
This project is released under a {PUBLIC} License.

=== Contributing
To contribute to this project please contact: sgfpcb@gmail.com

=== BOM

|===
| ID | Part name       | Part number | Quantity
| A1 | M5 Atom S3      |             | 1    
| A2 | M5 Relay Module |             | 1             
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
