:Author: ard12sgf1960
:Email: sgfpcb@gmail.com
:Date: 05/11/2023
:Revision: version#1.0
:License: Public Domain

= Project: {Remote relay control via Arduino IOT Cloud}

Control an M5 Relay Module using a M5 Atom S3 connected to Arduino IOT

== Step 1: Installation

Connect the Relay Module to the Atom

== Step 2: Assemble the circuit

1. Upload the code contained in this sketch on to your board
2. Using a separate device connect to WiFi_Select network
3. In the webpage that opens, select your network
4. Enter the password for the network
5. Once connected navigate to your Arduino Dashboard to remotely control device
6. Alternatively, press the screen to toggle output

=== Folder structure

....
 M5_Atom_S3                  => Arduino sketch folder
  ├── M5_Atom_S3_nov05a.ino  => main Arduino file
  ├── thingProperties.h      => Arduino created library
  ├── arduino_secrets.h      => library that contains WiFi Credentials
  ├── WiFiManage.h           => library to enable connection to any WiFI network
  ├── atomHelper.h           => library file to manager the Atom
  ├── relayHelper.h          => library file to manage the Relay module
  └── WiFiHelper.h           => library file to manage internet connection  
....

=== License
This project is released under a {PUBLIC} License.

=== Contributing
To contribute to this project please contact: sgfpcb@gmail.com

=== BOM

|===
| ID | Part name       | Part number | Quantity
| A1 | M5 Atom S3      |             | 1    
| A2 | M5 Relay Module |             | 1             
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
