#include "arduino_secrets.h"
/* 
Sketch generated by the Arduino IoT Cloud Thing "Untitled"
https://create.arduino.cc/cloud/things/6cde6503-fff6-4349-956d-8c245b12d16a 

Arduino IoT Cloud Variables description

The following variables are automatically generated and updated when changes are made to the Thing

int screenBrightness;
int pushButton;
bool relayOne;
bool relayTwo;

Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
which are called when their values are changed from the Dashboard.
These functions are generated with the Thing and added at the end of this sketch.
*/

/**************************************************************************************
* Description:  Arduino CLoud control of M5 relay unit using the Atom S3
* Sketch:       Relay_Control_WiFi.ino
* Version:      1.0
* Version Desc: Original Version. Using WiFi Manager to connect to any network was too big after library chnages
*               See Relay_Control_jan30a.ino for orginal sketch
*               This version just uses WiFi.h to connect
*               Screen on/off via relayTwo cloud variable
*               Added a restart timer if network disconnected
*               Forced the cloud variables ar device start
*               2025-02-12 Added a screen brightness cloud variable to change the device's screen brightness
*               2025-02-19 Added an Arduino IOT Schedule to turn on and off the relay
* Board:        Atom S3
* Author:       Steve Fuller
* Website:      https://github.com/SF1960/Atom_S3_Relay.git
* Comments      
***************************************************************************************/
//Arduino Libraries
#include <WiFi.h>
#include <M5AtomS3.h>

//Local libraries
#include "WiFiHelper.h"
#include "thingProperties.h"
#include "atomHelper.h"
#include "relayHelper.h"

unsigned long Reconnect = 1000 * 60 * 2; // 2 minute delay before restart
unsigned long PreviousRestartMillis = 0;

// start up variables
bool screen = true;                      // screen on variable

void setup() {

  Serial.begin(115200);                  // Initialize serial and wait for port to open:
  delay(1500); 

  atom::setup();                         // start the AtomS3, obtain screen width and height, and set relay cloud variables to default
  atom::connecting();                    // display connecting information

  bool connected = wifi::connect();      // use WiFi.h library to connect to an available WiFi network
 
  initProperties();                      // Defined in thingProperties.h

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);   // Connect to Arduino IoT Cloud
  
  setDebugMessageLevel(2);               // Arduino Library Debug Message Level
  ArduinoCloud.printDebugInfo();         // print debug messages

  atom::defaultScreen();                 // show the default screen
  relay::setup();                        // intialise the relay module

  Serial.println("Setup complete");
}
 
void loop() {

  ArduinoCloud.update();                  // update the cloud every loop of the code

  // if in automatic mode (schedule)
  if(inAuto==true){
    
    // check on and off time
    if (schedule.isActive()) {
       // whenever the job is "active", turn on the Relay
      relay::relay1_ON();
    } else {
       // whenever the job is "not active", turn off the Realy
      relay::relay1_OFF();
    }
    
  }

  /*
  Code to display one of two screens
  1. A connected screen
  2. A disconnected screen
  */
  // show the ~ symbol on the display when connected to Arduino
  if(ArduinoCloud.connected()){

    AtomS3.Lcd.setTextSize(2);
    AtomS3.Lcd.setTextColor(CYAN);
    AtomS3.Lcd.drawString("~", 13, 57, 2);
    AtomS3.Lcd.drawString("~", 100, 57, 2);

    time_read = ArduinoCloud.getLocalTime();

  } else {

    // overwrite the ~ symbol with black when NOT connected to Arduino
    AtomS3.Lcd.setTextSize(2);
    AtomS3.Lcd.setTextColor(BLACK);
    AtomS3.Lcd.drawString("~", 13, 57, 2);
    AtomS3.Lcd.drawString("~", 100, 57, 2);
    atom::screenOn();                    // force display ON when not connected to Arduino

    /* 
    * If not connected to Arduino then wait for Reconnect minutes
    * and restart the device and attempt to connect again
    */
    unsigned long CurrentRestartMillis = millis();
    if (CurrentRestartMillis - PreviousRestartMillis >= Reconnect) {

      PreviousRestartMillis = CurrentRestartMillis;
      ESP.restart();

    }

  }

  /*
  Read the state of the pushbutton
  When the screen button is released
  toggle the relay state
  */
  AtomS3.update();

   if (AtomS3.BtnA.wasReleased()) {     // if screen pressed
     if(inAuto==false){                 // if not in auto
       relay::latchRelay();             // toggle the relay     
     }
   }

} // loop()

// function to toggle the relay. Called by Arduino Cloud Dashboard/Thing
void onRelayOneChange()  {
  if(inAuto==false){         // if inAuto then do not allow manual button press
    relay::latchRelay();     // toggle the relay 
  }
}

// turn on and off the screen. Called by Arduino Cloud Dashboard/Thing
void onRelayTwoChange()  {

  if (screen == true){
    atom::screenOff();
    screen = false;
  } else {
    atom::screenOn();
    screen = true;
  }

}

/*
Change the screen brightness. Called by Arduino Cloud Dashboard/Thing
Turn on the screen
Set the brightness
*/
void onScreenBrightnessChange() {
  screen = true;
  atom::screenOn();
  atom::brightness();
}


/*
  Since Schedule is READ_WRITE variable, onScheduleChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onScheduleChange()  {
  // Add your code here to act upon Schedule change
}
/*
  Since InAuto is READ_WRITE variable, onInAutoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onInAutoChange()  {
  // Add your code here to act upon InAuto change
  inAuto != inAuto;
  
  if(inAuto==true){
      AtomS3.Lcd.fillRect(40, 45, 60, 40, BLACK);
      AtomS3.Lcd.setTextColor(GREEN);
      AtomS3.Lcd.setTextSize(2);
      AtomS3.Lcd.drawString("AUT", 43, 50, 2);
      AtomS3.Lcd.drawRoundRect(35, 45, 60, 40, 3, BLUE);
      AtomS3.Lcd.drawRoundRect(0, 0, width, height, 5, BLUE); 
      AtomS3.Lcd.fillRect(5, 105, width - 10, 20, BLACK); // erase the > press < text at the bottom of the screen
      AtomS3.Lcd.setTextSize(1);
      AtomS3.Lcd.drawString(">  Schedule  <", 13, 108, 2);
  } else {
      AtomS3.Lcd.fillRect(40, 45, 60, 40, BLACK);
      AtomS3.Lcd.setTextSize(2);
      AtomS3.Lcd.setTextColor(GREEN);
      AtomS3.Lcd.drawString("OFF", 43, 50, 2);
      AtomS3.Lcd.drawRoundRect(35, 45, 60, 40, 3, GREEN);
      AtomS3.Lcd.drawRoundRect(0, 0, width, height, 5, GREEN); 
      AtomS3.Lcd.fillRect(5, 105, width - 10, 20, BLACK); // erase the > press < text at the bottom of the screen
      AtomS3.Lcd.setTextSize(1);
      AtomS3.Lcd.drawString("> Press screen <", 13, 108, 2);
  }
}
