// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5c24f4f5-0661-48fd-8311-8f5d449cb30e";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelayOneChange();
void onRelayTwoChange();

int pushButton;
bool relayOne;
bool relayTwo;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pushButton, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relayOne, READWRITE, ON_CHANGE, onRelayOneChange);
  ArduinoCloud.addProperty(relayTwo, READWRITE, ON_CHANGE, onRelayTwoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
